### ISSUE TITLE
Invalid parameters(Currency Not Supported By Merchant Account)

### ISSUE THREAD

**Issue by juniel** [ktleow/ipay88#2]
i'm currently working on a project that require payment gateway and when i'm testing it on localhost this error appear. how do i solve this?
![untitled](https://cloud.githubusercontent.com/assets/12273177/16182208/f0abb190-36d5-11e6-9463-ed303aaa6a49.png)

or, there is something that i need to configure before use this code?
thank you in advance.

**Comment by ktleow** [comment]
I'm sorry I have not been maintaining this code for a long time. I do not use iPay88 anymore, please contact their support team for technical support.
